/*
 * This file is generated by jOOQ.
 */
package pl.michal.olszewski.jooqsample.db;


import javax.annotation.Generated;
import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sequences {

  /**
   * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_25386F2D_462E_42A0_8A11_14423346C0EA</code>
   */
  public static final Sequence<Long> SYSTEM_SEQUENCE_25386F2D_462E_42A0_8A11_14423346C0EA = new SequenceImpl<Long>("SYSTEM_SEQUENCE_25386F2D_462E_42A0_8A11_14423346C0EA", Public.PUBLIC,
      org.jooq.impl.SQLDataType.BIGINT);

  /**
   * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_494F13E3_5228_4508_A01F_A7CEEA206135</code>
   */
  public static final Sequence<Long> SYSTEM_SEQUENCE_494F13E3_5228_4508_A01F_A7CEEA206135 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_494F13E3_5228_4508_A01F_A7CEEA206135", Public.PUBLIC,
      org.jooq.impl.SQLDataType.BIGINT);

  /**
   * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_995D1763_CBC6_4F8E_A3DD_46B801F6589B</code>
   */
  public static final Sequence<Long> SYSTEM_SEQUENCE_995D1763_CBC6_4F8E_A3DD_46B801F6589B = new SequenceImpl<Long>("SYSTEM_SEQUENCE_995D1763_CBC6_4F8E_A3DD_46B801F6589B", Public.PUBLIC,
      org.jooq.impl.SQLDataType.BIGINT);
}
