/*
 * This file is generated by jOOQ.
*/
package pl.michal.olszewski.jooqsample.db;


import javax.annotation.Generated;

import pl.michal.olszewski.jooqsample.db.tables.Customer;
import pl.michal.olszewski.jooqsample.db.tables.Product;
import pl.michal.olszewski.jooqsample.db.tables.Reservation;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = pl.michal.olszewski.jooqsample.db.tables.Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.PRODUCT</code>.
     */
    public static final Product PRODUCT = pl.michal.olszewski.jooqsample.db.tables.Product.PRODUCT;

    /**
     * The table <code>PUBLIC.RESERVATION</code>.
     */
    public static final Reservation RESERVATION = pl.michal.olszewski.jooqsample.db.tables.Reservation.RESERVATION;
}
