/*
 * This file is generated by jOOQ.
*/
package pl.michal.olszewski.jooqsample.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product implements Serializable {

    private static final long serialVersionUID = -1163305272;

    private Long   id;
    private String name;
    private Long   customerId;

    public Product() {}

    public Product(Product value) {
        this.id = value.id;
        this.name = value.name;
        this.customerId = value.customerId;
    }

    public Product(
        Long   id,
        String name,
        Long   customerId
    ) {
        this.id = id;
        this.name = name;
        this.customerId = customerId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(customerId);

        sb.append(")");
        return sb.toString();
    }
}
