/*
 * This file is generated by jOOQ.
 */
package pl.michal.olszewski.jooqsample.db.tables.pojos;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Reservation implements Serializable {

  private static final long serialVersionUID = 469555749;

  private Long id;
  private String description;
  private String name;

  public Reservation() {
  }

  public Reservation(Reservation value) {
    this.id = value.id;
    this.description = value.description;
    this.name = value.name;
  }

  public Reservation(
      Long id,
      String description,
      String name
  ) {
    this.id = id;
    this.description = description;
    this.name = name;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Reservation (");

    sb.append(id);
    sb.append(", ").append(description);
    sb.append(", ").append(name);

    sb.append(")");
    return sb.toString();
  }
}
